
package victor.training.ms.shared;

public enum OrderStatus {
  AWAITING_PAYMENT,

  PAYMENT_FAILED,
  PAYMENT_APPROVED,

  WAITING_FOR_TRACKING_NUMBER, // TODO :)

  SHIPPING_IN_PROGRESS,
  SHIPPING_FAILED,
  SHIPPING_COMPLETED
}
