spring.application.name: gateway
server.port: 80
spring:
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://localhost:8082
          predicates:
            - Path=/customer/**

        - id: catalog
          uri: lb://catalog
          predicates:
            - Path=/catalog/**
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/payment/**
        - id: shipping
          uri: lb://shipping
          predicates:
            - Path=/shipping/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**