spring.application.name: gateway
server.port: 80

spring:
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customer/**
#          filters:
#            - AddRequestHeader=Authorization, Basic dXNlcjp1c2Vy
        - id: catalog
          # lb:// = Load Balancing = send round-robin requests to all instances of catalog registered with Eureka
          uri: lb://catalog
          predicates:
            - Path=/catalog/**
        - id: stock
          uri: lb://inventory
          predicates:
            - Path=/stock/**
        - id: shipping
          uri: lb://shipping
          predicates:
            - Path=/shipping/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
        - id: notification
          uri: lb://notification
          predicates:
            - Path=/notification/**
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/payment/**
