server.port: 8084
spring.application.name: notification

spring.cloud.function.definition: onOrderStatusChanged
spring.cloud.stream.bindings:
  onOrderStatusChanged-in-0:
      destination: OrderStatusChangedEvent
      group: ${spring.application.name}

