server.port: 8088

#app name is registers in Eureka and used by other ms when calling you
spring.application.name: order

spring.cloud.function.definition: onPaymentResultEvent;onShippingResultEvent;onShippingAcceptedEvent
spring.cloud.stream.bindings:
  onPaymentResultEvent-in-0:
    destination: PaymentResultEvent
    group: ${spring.application.name}
  onShippingResultEvent-in-0:
    destination: ShippingResultEvent
    group: ${spring.application.name}
#    consumer:
#      concurrency: 10
  OrderStatusChangedEvent-out:
    destination: OrderStatusChangedEvent
  requestTrackingNumber-out:
    destination: RequestShipping
  onShippingAcceptedEvent-in-0:
    destination: ShippingAcceptedEvent
    group: ${spring.application.name}
spring:
  cloud:
    openfeign:
      client:
        config:
          catalog:
            connectTimeout: 10000
            readTimeout: 10000