apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    id: 1
    uid: "-zxB4tSSk"
    orgId: 1
    type: "prometheus"
    typeName: "Prometheus"
    typeLogoUrl: "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
    access: "proxy"
    url: "http://prometheus:9090"
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: "POST"
      timeInterval: "1s"
    readOnly: false
