kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: microservices
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: KubeletConfiguration
    systemReserved:
      cpu: 100m
      memory: 100Mi
- role: worker
- role: worker

