server.port: 8086
spring.application.name: shipping
spring.cloud.openfeign.client.config:
  shipping-provider:
    url: http://localhost:9999

spring.cloud.function.definition: requestShipmentListener
spring.cloud.stream.bindings:
  ShippingResultEvent-out:
    destination: ShippingResultEvent
  requestShipmentListener-in-0:
    destination: RequestShipping
    group: ${spring.application.name}
    consumer:
      concurrency: 2
  requestShipmentListener-out-0:
    destination: ShippingAcceptedEvent
