server.port: 8761
eureka:
  client:
    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    renewal-percent-threshold: 0.85
  instance:
    lease-renewal-interval-in-seconds: 5

spring:
  boot:
    admin:
      context-path: /admin