server.port: 8085
spring.application.name: payment

spring.cloud.openfeign.client.config:
  payment-gateway:
    url: http://localhost:9999.default.loggerLevel
spring.cloud.stream.bindings:
  PaymentResultEvent-out:
    destination: PaymentResultEvent
